### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by seantrane** [codejamninja/yo-option-or-prompt#1]
Had the following error when using this script (via `generator-github-project`):

```sh
events.js:167
      throw er; // Unhandled 'error' event
      ^

ReferenceError: regeneratorRuntime is not defined
    at /Users/.../node_modules/yo-option-or-prompt/lib/index.js:10:46
    at Object.<anonymous> (/Users/.../node_modules/yo-option-or-prompt/lib/index.js:70:2)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/.../initializing.js:12:31)
Emitted 'error' event at:
    at Immediate.setImmediate (/Users/.../node_modules/yeoman-generator/lib/index.js:433:22)
    at runCallback (timers.js:693:18)
    at tryOnImmediate (timers.js:664:5)
    at processImmediate (timers.js:646:5)
```

**Comment by clayrisser** [comment]
Did this fix your error?

**Comment by clayrisser** [comment]
I think the regenerator runtime error is because it requires [babel-polyfill](https://www.npmjs.com/package/babel-polyfill) to be imported.
I could add [idempotent-babel-polyfill](https://github.com/codejamninja/idempotent-babel-polyfill) so everyone isn't forced to require babel-polyfill.

**Comment by clayrisser** [comment]
Commit 44baaa7c9dee494b1132aabb05085fc33a71aaee should have fixed this. Please updated to `0.2.0` and let me know if it works.

**Comment by clayrisser** [comment]
Can you confirm if this worked?
